apiVersion: v1
kind: Service
metadata:
  labels:
    name: pdf-chatbot-backend-service
  name: pdf-chatbot-backend-service
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    name: pdf-chatbot-backend
  type: ClusterIP