apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - frontend/pdf-chatbot-frontend.yaml
  - backend/pdf-chatbot-backend.yaml
  - backend/backend-service.yaml
  - frontend/frontend-service.yaml
  - peresistent-volume.yaml
  - pvc.yaml
secretGenerator:
- name: pdf-chatbot-secrets
  envs:
    - secrets-env.yaml
configMapGenerator:
- name: pdf-chatbot-config
  envs:
    - config.yaml