apiVersion: v1
kind: PersistentVolume
metadata:
  name: pdf-chatbot-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/mnehete32/workspace/pdf_chatbot/pdfs/"