apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: pdf-chatbot
  name: pdf-chatbot
spec:
  ports:
  - port: 7860
    protocol: TCP
    targetPort: 7860
  selector:
    name: pdf-chatbot
  type: NodePort
status:
  loadBalancer: {}
