apiVersion: v1
kind: Service
metadata:
  labels:
    name: pdf-chatbot-frontend-service
  name: pdf-chatbot-frontend-service
spec:
  ports:
  - port: 7860
    protocol: TCP
    targetPort: 7860
  selector:
    name: pdf-chatbot-frontend
  type: NodePort